#!/usr/bin/sh

TARGET_DIR=$(~/.local/bin/etabli_board -n dir -q)
if [[ "$TARGET_DIR" == "" ]]; then
    TARGET_DIR=$(xdg-user-dir PICTURES)
fi
FILE_NAME=$TARGET_DIR/$(uuidgen).png
grim  -g "$(slurp)" "$FILE_NAME"
if [[ -f $FILE_NAME ]]; then
    notify-send "$FILE_NAME has been created"
else
    echo "capture cancelled"
fi
