#+TITLE: Emacs Configuration
#+START U: overview
#+SETUPFILE: ../setup.org
#+PROPERTY: header-args  :tangle ~/.emacs.el  :noweb yes


* Installation :stable:
** Main setup
The emacs version bundled with ubuntu is not compiled with flags that I need, meaning I need to install emacs from sources and compile it myself. No big deal, it is very straight forward---in fact, let's automatize it with a small script: [[./install.zsh]]. The rest of this section builds this script.

First, we set the shebang and store the emacs version in an appropriate variable.

#+BEGIN_SRC zsh :tangle install.zsh
  #!/usr/bin/env zsh

  VERSION=30.2
#+END_SRC

Then, we check for the presence of the emacs executable, and simply exit if it is found: we don't need to do anything.

#+BEGIN_SRC zsh :tangle install.zsh
  if [[ -a ./emacs-$VERSION/src/emacs ]]; then
      echo "emacs-$VERSION is already present, no need to download/compile it"
      return
  fi
#+END_SRC

** Download (if necessary)
Then, we ensure that we have the emacs version we want. This done by testing the presence of the appropriate folder. If it is not found, then we download the correct archive from an emacs mirror, and uncompress it.

#+BEGIN_SRC zsh :tangle install.zsh
  if [[ ! -a ./emacs-$VERSION ]]; then
      echo "directory not found, downloading"
      wget https://ftp.snt.utwente.nl/pub/software/gnu/emacs/emacs-$VERSION.tar.xz
      tar -xvf ./emacs-$VERSION.tar.xz
  else
      echo "no need to download"
  fi
#+END_SRC
** Custom compilation
Finally, we compile it. the compilation flags are a combination of the suggestions from https://www.reddit.com/r/emacs/comments/mh5l9y/comment/gsz2ey3/ (for wayland support) and https://www.rahuljuliato.com/posts/compiling_emacs_30_1 (for general image support), as well as, crucially, the flag enabling =treesitter= and native compilation.

I don't use treesitter yet but I want to have it as an option. I do rely heavily on the "native compilation" of emacs lisp for performances though.

Compilation is then performed using =make=.

#+BEGIN_SRC zsh :tangle install.zsh
  cd emacs-$VERSION/
  ./configure --with-native-compilation \
                --with-tree-sitter \
                --with-modules \
                --with-threads \
                --with-mailutils \
                --with-gif \
                --with-png \
                --with-jpeg \
                --with-rsvg \
                --with-tiff \
                --with-imagemagick \
                --without-x \
                --with-pgtk
    make clean
    make -j8
#+END_SRC

* Core setup

#+BEGIN_SRC emacs-lisp 
  ;;; -*- lexical-binding: t; -*- 

  (eval-when-compile (require 'use-package))
#+END_SRC
** Use-package
  
#+BEGIN_SRC emacs-lisp 
  (require 'package)
  (setopt package-check-signature nil)
  (add-to-list 'package-archives '("melpa-stable" . "https://stable.melpa.org/packages/") t)
  (add-to-list 'package-archives '("melpa-backup" . "http://www.mirrorservice.org/sites/stable.melpa.org/packages/") t)
  (require 'use-package)
#+END_SRC

** Ensuring efficiency :attentionNeeded:
Following the advice of the [[https://github.com/jamescherti/compile-angel.el][compile-angel]] developer, I start with the following. It ensures that all packages are compiled "natively" (i.e. into machine language), and that the resulting programs are used.

This step requires for emacs to be compiled by hand with the appropriate option, as is done in [[*Custom compilation]].

The initial comment is needed to remove a compilation warning (see e.g. [[https://github.com/agda/agda/issues/7730][this discussion on github]]).

#+BEGIN_SRC elisp
  (use-package compile-angel
    :ensure t
    :demand t
    
    :config
    ;; Set `compile-angel-verbose' to nil to disable compile-angel messages.
    ;; (When set to nil, compile-angel won't show which file is being compiled.)
    (setq compile-angel-verbose t)

    ;; Uncomment the line below to compile automatically when an Elisp file is saved
    ;; (add-hook 'emacs-lisp-mode-hook #'compile-angel-on-save-local-mode)

    ;; The following directive prevents compile-angel from compiling your init
    ;; files. If you choose to remove this push to `compile-angel-excluded-files'
    ;; and compile your pre/post-init files, ensure you understand the
    ;; implications and thoroughly test your code. For example, if you're using
    ;; the `use-package' macro, you'll need to explicitly add:
    ;; (eval-when-compile (require 'use-package))
    ;; at the top of your init file.
    ;(push "~/.emacs.el" compile-angel-excluded-files)

    ;; A global mode that compiles .el files before they are loaded
    ;; using `load' or `require'.
    (compile-angel-on-load-mode 1))

  ;; Ensure Emacs loads the most recent byte-compiled files.
  (setopt load-prefer-newer t)

  ;; Make Emacs Native-compile .elc files asynchronously by setting
  ;; `native-comp-jit-compilation' to t.
  (setopt native-comp-jit-compilation t)
#+END_SRC
** Startup
The inital-scratch-message is added by hand as it would just be added automatically otherwise. Miscellaneous appearance stuff follows:
+ remove startup screen https://stackoverflow.com/questions/744672/unable-to-hide-welcome-screen-in-emacs
+ remove toolbars http://kb.mit.edu/confluence/display/istcontrib/Disabling+the+Emacs+menubar%2C+toolbar%2C+or+scrollbar
+ initial buffer: https://emacs.stackexchange.com/questions/15081/programming-of-initial-buffer-choice
+ don't check for the "safety" of local variables

The signature verification is disabled because of the OS on the desktop being too old.
#+BEGIN_SRC emacs-lisp 
  (setopt initial-buffer-choice "~/org/todo.org"
          inhibit-startup-screen t)

  (menu-bar-mode -1) 
  (tool-bar-mode -1)
  (setq enable-local-variables :all)
  (require 'cl-lib)
#+END_SRC
** Appearance
*** Font
Using [[https://github.com/tonsky/FiraCode/wiki/Emacs-instructions][fira code]] because it looks nice:
#+BEGIN_SRC emacs-lisp
(add-to-list 'default-frame-alist '(font . "Fira Code" ))
(set-face-attribute 'default t :font "Fira Code")
#+END_SRC

*** Color theme
I made my own theme called =cyanide-light=. I use this one.

#+BEGIN_SRC emacs-lisp
(load-file "~/dotfiles/emacs/cyanide-light-theme.el")
(load-theme 'cyanide-light t)
#+END_SRC

*** Line behaviour
**** Numbering
=Linum-Mode= being bothersome, I switched to the built-in =display-line-number-mode= (as suggested [[https://www.emacswiki.org/emacs/LineNumbers][here]]).
#+BEGIN_SRC emacs-lisp 
(global-display-line-numbers-mode 1)
#+END_SRC

**** Line wrapping
In order for lines not to spill out of the window, we use the following.

#+BEGIN_SRC emacs-lisp 
(global-visual-line-mode t)
#+END_SRC

**** Current line
The current line is highlighted by being of a slightly different color.

#+BEGIN_SRC emacs-lisp 
(global-hl-line-mode)
#+END_SRC

*** Finding Cursor
In order to make the cursor easier to find (e.g. when new emacs windows are opened, =beacon= can help (see [[https://github.com/Malabarba/beacon][its homepage]]). It is a package (that must be installed). The following activates the corresponding global mode, and ensures that the beacon blinks whenever the emacs window or the actual window is changed.

#+BEGIN_SRC emacs-lisp 
  (use-package beacon
    :ensure t
    :config
    (beacon-mode)
    (setq beacon-blink-when-window-changes t
          beacon-blink-when-focused t
          beacon-color "<<../setup.org:focus-color()>>"
          beacon-size 15
          beacon-blink-when-window-scrolls t))
#+END_SRC

*** Mode line
The mode line is based on the [[https://gitlab.com/jessieh/mood-line][mood-line]] package. The default appearance is quite good in my opinion, but we can do better.

The default setup is essentially straight from the documentation.

#+BEGIN_SRC elisp
  (use-package mood-line
    :ensure t
    
    :config
    (mood-line-mode)

    ;; Use pretty Fira Code-compatible glyphs
    :custom
    (mood-line-glyph-alist mood-line-glyphs-fira-code))
#+END_SRC

We then improve upon the default appearance. The idea is to display more information than just the basic buffer name: the document title in an org document, or the full path to a file if the buffer corresponds to a file. Then, said path should be relative to a project root when relevant. Finally, the project name itself should be displayed prominently.

First, we need some functions to display path

**** Path display

#+BEGIN_SRC elisp
  (defun pi2-6/mood-line-split-path()
    (let ((full-path (file-name-split (buffer-file-name))))
      (if (member "home" full-path)
          (nthcdr
           (length (file-name-split (expand-file-name "~")))
           full-path)
        full-path)))


  (defun pi2-6/mood-line-pretty-path(split-path)
    (s-concat
     (when (< 1 (length split-path))
       (propertize (s-concat
                    " "
                    (apply #'file-name-concat (butlast split-path)))
                   'face 'mode-line-path))
     (propertize (s-concat "/" (car (last split-path)) " ")
                 'face 'mode-line-file-name)))


  (defun pi2-6/mood-line-title()
    ; handling potential project name
    (s-concat
     (when (boundp 'meuporg-project-name)
        (propertize (s-concat " " meuporg-project-name " ") 'face 'structure-highlight))
     (cond 
      ((string= major-mode "org-mode")
       (propertize (s-concat " " (org-get-title) " ")
                   'face '(:inherit 'org-document-title :height 0.5)))
      ((string-match "\\*.*\\*" (buffer-name))
       (propertize (s-concat " " (buffer-name) " ")
                   'face 'mode-line-star-buffer))
      ((boundp 'meuporg-project-name)
       (pi2-6/mood-line-pretty-path (file-name-split (file-relative-name (buffer-file-name) (projectile-project-root)))))
      ((buffer-file-name)
       (pi2-6/mood-line-pretty-path (pi2-6/mood-line-split-path)))
      (t
        (buffer-name)))))


    (setopt mood-line-format
            '(
              (#1=" " (mood-line-segment-modal) " "
                  (or (mood-line-segment-buffer-status) " ") " "
                  (pi2-6/mood-line-title) "  " (mood-line-segment-anzu)
                  "  " (mood-line-segment-multiple-cursors) "  "
                  (mood-line-segment-cursor-position) " "
                  (mood-line-segment-scroll) "")
              ((mood-line-segment-vc) "  " (mood-line-segment-major-mode) "  "
               (mood-line-segment-misc-info) "  " (mood-line-segment-checker) "  "
               (mood-line-segment-process) "  " #1#)))
#+END_SRC
** Scripts
In order for this system to work well, the scripts in [[./helper-scripts/]] need to be copied somewhere in the path, execution rights added, and extension removed.
** File Handling
Emacs, by default, asks for confirmation before following symbolic
links. It is annoying; the following gets rid of this ([[https://emacs.stackexchange.com/questions/41286/follow-symlinked-directories-in-dired][source]]).

#+BEGIN_SRC emacs-lisp 
(setq find-file-visit-truename t)
#+END_SRC
* Org
** Common settings
#+BEGIN_SRC elisp
  (setopt org-startup-indented t
                org-pretty-entities t
                org-hide-emphasis-markers t
                org-startup-with-inline-images t
                org-image-actual-width '(300)
                org-tags-column 10
                org-link-elisp-confirm-function nil
                org-ellipsis "⤵"
              )
#+END_SRC

It is possible to ensure that LaTeX is always rendered by setting =org-startup-with-latex-preview= to =t=, but this has a significant time penalty. Better not to.
Requiring =org-mouse= ensures that we can fold/unfold org-headings by clicking on the markers.

#+BEGIN_SRC elisp
  ;; (use-package org-superstar
  ;;   :ensure t
  ;;   )

  (use-package org-fragtog
    :ensure t

    :after org

    :custom
    (org-startup-with-latex-preview nil)

    :custom
    (org-format-latex-options
     (plist-put org-format-latex-options :scale 1.5)
     (plist-put org-format-latex-options :foreground 'auto)
     (plist-put org-format-latex-options :background 'auto))
    )

  (use-package org
    :ensure t
    
    :mode
    (("\\.org$" . org-mode))
    
    :hook
    (org-mode . (lambda ()
                  (org-fragtog-mode)
                  ;(org-superstar-mode)
                  (org-num-mode)))
    )

  (require 'org-mouse)
  (require 'org-attach)
#+END_SRC
** Better ids
#+BEGIN_SRC elisp
(setopt org-id-ts-format "%Y-%m-%d-%a(%H:%M:%S)%N")
(setopt org-attach-id-dir "files/")
(setopt org-id-method 'ts)

#+END_SRC
** Data Storage
*** Tags
The idea is to have mere annotations in files that are not intended to help with keeping track of projects (typically, dotfiles such as this one). These are of two types. The first documents the state of the heading:
- ongoingWork :: I am currently working on it;
- attentionNeeded :: I am not working on it at the moment but it will need to happen at some point;
- stable :: I am happy with the current state of this heading, and am not plann ing to modify it.
- hack :: If I am not planning to modify something *a priori*, but am not super happy with the solution I used.

A permanent list of tags is specified first. It has to be set with =setopt=, otherwise it doesn't work.

#+BEGIN_SRC elisp
  (setopt org-tag-persistent-alist
         '((:startgroup)
           ("state")
           (:grouptags)
           ("ongoingWork" . ?o)
           ("attentionNeeded" . ?n)
           ("stable" . ?s)
           ("hack" . ?h)
           (:endgroup)
           (:startgroup)
           ("type")
           (:grouptags)
           ("paper" . ?a)
           ("people" . ?e)
           ("project" . ?r)
           (:endgroup)
           (:startgrouptag)
           ("mine")
           ("sok")
           (:endgrouptag)
           ))
#+END_SRC

Same thing with =org-tag-faces=, which also needs to be set with =setopt=. It simply describes which face to use for each of these tags.

#+BEGIN_SRC elisp
  (setopt org-tag-faces
          '(
            ("ATTACH" . 'org-link)

            ("ongoingWork" . (:background "yellow" :foreground "dim gray"))
            ("attentionNeeded" . (:background "orange" :foreground "dim gray"))
            ("stable" . (:foreground "chartreuse2"))
            ("hack" . (:foreground "tomato"))

            
            ("mine" . (:background "black" :foreground "white" :distant-foreground "black"))
            ("sok" . (:background "white" :foreground "red"))

            ("sym" . (:background "brown" :foreground "white" :distant-foreground "brown" ))
            ("stap" . (:background "dark orange" :foreground "white" :distant-foreground "dark orange"))
            ("light" . (:background "sienna" :foreground "white" :distant-foreground  "sienna"))
            
            ("mode" . (:background "magenta" :foreground "black"))

            ("mpc" . (:background "rosy brown" :foreground "black"))
            ("zk" . (:background "coral" :foreground "black"))
            ("fhe" . (:background "tomato" :foreground "black"))
            ("tfhe" . (:background "light coral" :foreground "black"))
            
            ("sbox" . (:background "dark violet" :foreground "white" :distant-foreground "dark violet"))
            ("apn" . (:background "cyan" :foreground "black"))
            ("math" . (:background "deep sky blue" :foreground "black"))
            ("ccz" . (:background "steel blue" :foreground "white" :distant-foreground "steel blue"))
            
            ("posso" . (:background "chartreuse" :foreground "black"))
            ("differential" . (:background "green" :foreground "white" :distant-foreground "green" ))
            ("linear" . (:background "lime green" :foreground "black"))
            ("subspace" . (:background "medium spring green" :foreground "black"))
            
            ))

#+END_SRC

In order to allow the use off different colors in file vaults, it is possible to specify a local set of colors in the =dir-locals= file by creating a variable called =local-org-tag-faces=. Its content is added to the main =org-tag-faces= by the following snippet which was surprisingly hard to write. Indeed, =dir-locals= variables are only set *after* the major mode is setup. As a consequence, using its content requires the use of a later hook.

#+BEGIN_SRC elisp
  (add-hook
   'after-change-major-mode-hook
   (lambda ()
     (if (boundp 'local-org-tag-faces)
         (setopt org-tag-faces (append org-tag-faces local-org-tag-faces))))
   )
#+END_SRC

*** Opening image folders
It is nice to attach entire collections of pictures (e.g. to store and tag travel photos). Then, these shouldn't be attached and opened one by one, but instead folder by folder, each folder being opened as a slideshow. The =xsiv= program does just that, and is easy to script. The following functions grabs all the pictures in an attach directory and starts a slide show with them.

The options are
- r :: to recursively search subdirectories,
- S 3 :: to have a slide show where each picture remains for 3s before switching to the next,
- sf :: to have the pictures fill the available space without having their geometry altered.

#+BEGIN_SRC elisp
  (defun pi2-6/open-slide-show()
    "Assuming the attached data is a folder containing pictures,
  starts a slideshow with all of those."
    (shell-command (format "sxiv -r -S 3 -p -sf '%s' &" (org-attach-dir))))
#+END_SRC 

** Attach enhancement
Attachments are, by default, not openable with a simple mouse click. Furthermore, the corresponding headings don't look like links. A first approach may consist in adding an advice to the function making attachments to turn the heading into a link calling =org-attach-open=. It works, but when headings are displayed for instance in a consult mini-buffer, the full link is displayed, which is not great. Instead, I turn the ATTACH tag into a link which calls an appropriate function.

The following snippet makes the =ATTACH= tag clickable.

When clicking on a tag, the function =org-tags-view= is called if we are in an org-agenda file. I thus add an advice around this function which checks if the tag clicked is =ATTACH=, in which case it calls a custom function instead. Otherwise, it simply calls the "normal" =org-tags-view= function.

If we are not in an org-agenda-file, then the =org-open-at-mouse= function is called. Same advice is applied.

#+BEGIN_SRC elisp
  (require 'org)

  (defun pi2-6/attach-open()
    (interactive)
    (if (member "ATTACH" (org-get-tags))
        (if (member "images" (org-get-tags))
            (pi2-6/open-slide-show)
          (org-attach-open))))

  (advice-add 'org-open-at-mouse :around
              (lambda (oldfun &rest args)
                (if (and
                     (org-at-heading-p)
                     (member "ATTACH" (org-get-tags)))
                    (pi2-6/attach-open)
                    (apply oldfun args))))

  (advice-add 'org-tags-view :around
              (lambda (oldfun &rest args)
                (if (member "ATTACH" args)
                      (pi2-6/attach-open)
                  (apply oldfun args))))
#+END_SRC

We also need the following to be able to open attachments with better-ids.

#+BEGIN_SRC elisp
(defun pi2-6/org-attach-id-readable-format (id)
  "Translate an ID based on a readable timestamp to a folder-path.
Useful way of translation if ID is not generated based on ISO8601
timestamp, but on something easier to read where the month is separated
from the year.  Splits the attachment folder hierarchy into year-month,
the rest; the leading character of the rest being dropped."
  (and (< 10 (length id))
       (format "%s/%s"
               (substring id 0 7)
               (substring id 8))))

(setopt org-attach-id-to-path-function-list
        '(pi2-6/org-attach-id-readable-format
          org-attach-id-uuid-folder-format
          org-attach-id-ts-folder-format
          org-attach-id-fallback-folder-format))
 #+END_SRC
 
** Org babel
We need to enable the languages in babel. This is done as follows ([[https://emacs-orgmode.gnu.narkive.com/hmJIUIeQ/o-bug-org-babel-execute-src-block-no-org-babel-execute-function-for-python][source]]).
#+BEGIN_SRC emacs-lisp
  (org-babel-do-load-languages
   'org-babel-load-languages
   '((python . t)
     (C . t)
     (shell . t)))
#+END_SRC


Some more tweaks are needed though, in particular we need to tell
org-mode to use =python3= rather than =python= as a command. This is
done as [[https://emacs.stackexchange.com/questions/28184/org-mode-how-can-i-point-to-python3-5-in-my-org-mode-doc][here]]. We also org-mode not to ask for a confirmation everytime
we evaluate a code block.
#+BEGIN_SRC emacs-lisp
(setq org-babel-python-command "python3"
      org-confirm-babel-evaluate nil)
#+END_SRC
*** Regenerate main configuration file
Now that org-babel is setup, we can define the following function which tangles this file and then compiles the result. Useful when a change is made but we don't want to re-tangle all the files in this repository (meaning, running the [[../readme.org::*Updating configuration]] script).

#+BEGIN_SRC emacs-lisp
  (defun pi2-6/reset-config()
    (interactive)
    (with-current-buffer (find-file-noselect (file-truename "~/dotfiles/emacs/config.org"))
      (org-babel-tangle))
    (native-compile "~/.emacs.el"))
#+END_SRC

** Org :deactivated:
*** Capture
The capture templates for org-roam-capture are intended to send the notes in the correct folders, and of course to populate the notes with the correct template. At this stage, =roam= has the following subdirectories:
- projects :: Contains the meuporg-files for the ongoing projects.
- reviews :: self explanatory. 
- library :: contains solidified knowledge. 

#+BEGIN_SRC emacs-lisp :tangle no
(setopt org-roam-capture-templates
      '(
        ("p" "projects" plain (file "~/roam/templates/project.org")
         :target (file+head "projects/%<%Y%m%d%H%M%S>-${slug}.org"
                            "#+title: ${title}\n") :unnarrowed t)
        ("r" "review" plain (file "~/roam/templates/review.org")
         :target (file+head "reviews/%<%Y%m%d%H%M%S>-${slug}.org"
                            "#+title: ${title}\n") :unnarrowed t)
        ("l" "library" plain (file "~/roam/templates/library.org")
         :target (file+head "library/%<%Y%m%d%H%M%S>-${slug}.org"
                            "#+title: ${title}\n") :unnarrowed t)
        ))

#+END_SRC

*** Custom opening functions

#+BEGIN_SRC emacs-lisp  :tangle no
  (defun pi2-6/org-roam-find-library ()
      (interactive)
      (org-roam-node-find
       nil nil
       (lambda (node)
         (member "paper" (org-roam-node-tags node)))))

  (defun pi2-6/org-roam-find-review ()
      (interactive)
      (org-roam-node-find
       nil nil
       (lambda (node)
         (member "review" (org-roam-node-tags node)))))


  (defun pi2-6/org-roam-find-other ()
      (interactive)
      (org-roam-node-find
       nil nil
       (lambda (node)
         (not (or
               (member "review" (org-roam-node-tags node))
               (member "paper" (org-roam-node-tags node)))))))

  (defun pi2-6/org-roam-find-meuporg()
    (interactive)
    (if (boundp 'meuporg-file)
        (org-roam-id-open meuporg-file nil)))
#+END_SRC

*** use-package
The parameter =org-roam-completion-everywhere= means that every string can potentially be auto-completed into an org-roam link. Since most common words appear somewhere in the title of a note, this gets very annoying very quickly: best to disable it.

#+BEGIN_SRC elisp  :tangle no
  (use-package org-roam
    :ensure t
    :init
    (setopt org-roam-v2-ack t)
    :custom
    (org-roam-directory (file-truename "~/roam/"))
    (org-roam-completion-everywhere nil)
    (org-roam-capture-templates
     '(("d" "default" plain
        "%?"
        :if-new (file+head "%<%Y%m%d%H%M%S>-${slug}.org" "#+title: ${title}\n")
        :unnarrowed t)))
    
    
    :config
    (org-roam-db-autosync-enable))
#+END_SRC

** Vulpea
(vulpea-db-sync-full-scan)
#+BEGIN_SRC elisp
  (use-package vulpea
    :ensure t
    :config
    (setopt vulpea-db-sync-directories '("~/roam/"))
    (setopt vulpea-default-notes-directory "~/roam/")
    (setopt vulpea-db-sync-external-method 'auto)
    (vulpea-db-autosync-mode +1))

#+END_SRC

** Capture
Capturing information for the roam/vulpea directory is handled "by hand" as I couldn't get =org-capture= to do what I wanted. On the other hand, it is very easy to write dedicated =vulpea= creation functions, the specific choice of which to call then being decided using =transient=.
#+BEGIN_SRC elisp
  (defun pi2-6/capture-paper(title)
      "Capture a paper"
       (interactive "sPaper title: ")
       (vulpea-visit (vulpea-create title
                                    "papers/${timestamp}_${slug}.org"
                                    :tags '("paper"))))

    (defun pi2-6/capture-library(title)
      "Capture a note for the library"
       (interactive "sNote title: ")
       (vulpea-visit (vulpea-create title
                                    "library/${timestamp}_${slug}.org"
                                    :body "* Notes"
                                    :tags '("note"))))

      (defun pi2-6/capture-project(title)
      "Capture a note for a project"
       (interactive "sProject title: ")
       (vulpea-visit (vulpea-create title
                                    "projects/${timestamp}_${slug}.org"
                                    :head "#+MEUPFOLDER: "
                                    :body "* Diary  :noexport:"
                                    :tags '("ongoingWork"))))

      (defun pi2-6/capture-review(title)
      "Capture a review"
       (interactive "sReviewed paper title: ")
       (vulpea-visit (vulpea-create (format "%s (review)" title)
                                    "reviews/${timestamp}_${slug}.org"
                                    :body "* ${title} :review:ongoingWork: \nDEADLINE: \n:PROPERTIES:\n:ID: %(org-id-get-create)\n:END:\n* Files\n** main pdf\n* Diary  :noexport:")))
#+END_SRC

#+RESULTS:
: pi2-6/capture-review

#+BEGIN_SRC elisp
  
   (defun pi2-6/find-ongoingWork()
     "Selects a vulpea note with the ongoingWork tag"
     (interactive)
     (vulpea-visit (vulpea-select-from "to visit: "
                                       (vulpea-db-query-by-tags-some '("ongoingWork")))))

  (defun pi2-6/find-paper()
    "Find a paper within the vulpea/roam directory"
    (interactive)
    (vulpea-visit (vulpea-select-from "Select paper" (vulpea-db-query-by-tags-every '("paper")))))

  
  (defun pi2-6/find-attachment()
    "Find an attachment within the vulpea/roam directory"
    (interactive)
    (vulpea-visit (vulpea-select-from "Select attachment" (vulpea-db-query-by-tags-every '("attach")))))

  
#+END_SRC

  The selection function is then a simple =transient= function.

  #+BEGIN_SRC elisp
     (require 'transient)

     (transient-define-prefix pi2-6/vulpea-action()
       "What to capture?"
       [("f" "[f]find" vulpea-find)
        ("g" "find on[g]oingWork" pi2-6/find-ongoingWork)
        ("p" "new [p]aper" pi2-6/capture-paper)
        ("l" "new [l]ibrary entry" pi2-6/capture-library)
        ("o" "new pr[o]ject entry" pi2-6/capture-project)
        ("r" "new [r]eview" pi2-6/capture-review)
        ("i" "grab l[i]nk" vulpea-insert)
         ])
#+END_SRC

** Org links
#+BEGIN_SRC elisp
  (setopt
   org-file-apps
   '(
     ("\\.mm\\'" . default)
     ("\\.x?html?\\'" . default)
     ("\\.pdf::#\\([0-9]+\\)?" . "evince %s -i %1")
                                          ; ("\\.pdf::\\(\\?\\(:[[:alnum:]]\\|[[:space:]]\\|[[:punct:]]\\)+\\)?" . "evince %s -l \"%1\"")
     ("\\.pdf::\\([a-zA-Z0-9,.; ]+\\)?" . "evince %s -l \"%1\"")
     ("\\.pdf" . "evince %s")
     ("\\.mp4" . "vlc %s")
     ("\\.doc" . "libreoffice %s")
     ("\\.docx" . "libreoffice %s")
     ("\\.ods" . "libreoffice %s")
     ("\\.xls" . "libreoffice %s")
     ("\\.xlsx" . "libreoffice %s")
     ("\\.ppt" . "libreoffice %s")
     ("\\.pptx" . "libreoffice %s")
     (auto-mode . emacs)
     ))

  (setopt org-link-frame-setup
          '((vm . vm-visit-folder-other-frame)
            (vm-imap . vm-visit-imap-folder-other-frame)
            (gnus . org-gnus-no-new-news)
            (file . find-file)
            (wl . wl-other-frame)))

  (defun pi2-6/open-at-point()
    "Tries to open an org-link at point, and if it fails then tries to
   open the file at point."
    (interactive)
    (condition-case nil 
        (call-interactively 'org-open-at-point)
      (error (find-file-at-point))))
#+END_SRC

** Org-Agenda
*** Setting up org-agenda files :stable:
First, we need to specify where to look for TODO items. These are stored in org-roam files, but, in order to avoid to parse all of them (both for emacs and for myself), files that correspond to ongoing work have the corresponding tag set at the file level. Those that are finished are move to "stable", following the logic described in [[*Tags]]

The code exracting ongoing work from the vulpea/roam folder is easy to write.

#+BEGIN_SRC emacs-lisp
  (defun pi2-6/set-org-agenda-files ()
    "Set org-agenda-files to be a list containing the names of the files
  corresponding to org-roam nodes with the ongoingWork tag."
    (interactive)
    (setopt
     org-agenda-files
     (-uniq (mapcar 'vulpea-note-path (vulpea-db-query-by-tags-every '("ongoingWork"))))))

  (pi2-6/set-org-agenda-files)
#+END_SRC

    (consult-org-agenda "TODO=\"TODO\"")
*** TODO Customizing org-agenda view :ongoingWork:
Then, we need to configure what is displayed.

The following was largely made by Claude, and it works pretty well, but fontification doesn't for some reason. Org-super-agenda doesn't seem to want to work, but having a custom view for each "type" (bullshit, project, and review) could make sense.

The tag :ongoingWork: is what triggers the presence of a TODO item in the agenda list, so we remove its display by setting the =org-agenda-hide-tags-regexp= appropriately.

Ressources:
- Nicolas Rougier's configuration :: [[https://www.labri.fr/perso/nrougier/GTD/index.html]]

Each agenda view is set by calling a function (e.g. =agenda=), followed by some data (e.g., tags to include), and then a list of variable/value pairs (e.g, =(org-agenda-overriding-header "reviews")= to have "reviews" override the default header of this section of the agenda).

There seems to be a complication: =tags-todo= cannot display a deadline. I will have to it differently for reviews.

#+BEGIN_SRC elisp :tangle no
  (defun my/org-agenda-get-file-title (file)
    "Get #+title: from FILE."
    (with-current-buffer (find-file-noselect file)
      (or (cadr (assoc "TITLE" (org-collect-keywords '("title"))))
          (file-name-nondirectory file))))

  (my/org-agenda-get-file-title "~/roam/library/20251016155324-arion.org")

  (defun my/org-agenda-prefix-with-title ()
    "Return prefix with file title."
    (let* ((file (buffer-file-name (org-base-buffer (current-buffer))))
           (title (when file (my/org-agenda-get-file-title file))))
      (propertize (format "%-15s" (or title "")) 'face 'bold)))

  ;; (setopt org-agenda-prefix-format
  ;;         '((agenda . "%-12:c%?-12t% s")
  ;;           (todo . "%(my/org-agenda-prefix-with-title) %-20:b")
  ;;           (tags . "%-12:c")
  ;;           (search . " %i %-12:c")))

   (setopt org-agenda-prefix-format
      '((agenda . " %i %-12:c%?-12t% s")
        (todo   . "%(my/org-agenda-prefix-with-title)")
        (tags   . " %i %-12:c")
        (search . " %i %-12:c")))

  (setopt org-agenda-hide-tags-regexp "ongoingWork\\|review")

  ;; (setopt org-agenda-custom-commands '(("n" "Agenda and all TODOs" ((agenda "") (alltodo ""))))) ; the default

  (setopt org-agenda-custom-commands
      '(("g" "Reviews"
         ((agenda "review" ((org-agenda-overriding-header "Reviews")
                               (org-agenda-entry-types '(:deadline))
                               ))))))
          

#+END_SRC

#+RESULTS:
: my/org-agenda-prefix-with-title

* Projects
Setup projectile

#+BEGIN_SRC elisp
  (defun pi2-6-find-file-in-project-or-not()
    (interactive)
    (if (boundp 'meuporg-project-name)
        (projectile-find-file)
      (call-interactively 'find-file)))
#+END_SRC

#+BEGIN_SRC elisp
    (use-package projectile
      :ensure t

      :custom
      (projectile-globally-ignored-file-suffixes '("out" "pdf" "o" "aux" "pyc" "~"))
      (projectile-project-types nil)
      (projectile-completion-system 'auto)
      (projectile-require-project-root t)
      
      :config
      (projectile-mode)
      (define-key projectile-mode-map (kbd "C-x p") 'projectile-command-map)
      (projectile-register-project-type
       'meuporg-project '(".projectile")
       :project-file ".projectile"
       :compile "make")
      (setq projectile-indexing-method 'native)
      (setq projectile-enable-caching 'persistent)
      )

#+END_SRC

#+BEGIN_SRC elisp
  (load-file "~/dotfiles/emacs/meuporg.el")
  ;(print org-num-face)
  ;(print cyanide-num-face)
#+END_SRC
** Org export
The default style when exporting org to LATEX is very ugly; the following makes it better by removing ugly boxes and ensuring that the table of content does not interfere with the remainder of the content.
#+BEGIN_SRC elisp
  (setopt org-latex-with-hyperref "\\hypersetup{
    pdfauthor={%a},
    pdftitle={%t},
    pdfkeywords={%k},
    pdfsubject={%d},
    pdfcreator={%c}, 
    pdflang={%L},
    colorlinks=true,
    urlcolor=blue,
    linkcolor=blue,
    citecolor=red}")

    (setopt org-latex-toc-command "\\tableofcontents \\newpage

  ")
#+END_SRC
** LSP
Not very convincing, auctex should be all I need.

#+BEGIN_SRC elisp :tangle no
(use-package lsp-latex
  :ensure t
  :init
  (setq lsp-latex-texlab-executable "~/dotfiles/tools/texlab/texlab-bin")

  )
#+END_SRC

** Magit
#+BEGIN_SRC elisp
  (use-package magit
    :ensure t
    )
#+END_SRC

* Input/Editing handling
** Auto-completion
*** Orderless
From the [[https://github.com/oantolin/orderless][orderless documentation]]. 

#+BEGIN_SRC elisp
;; Optionally use the `orderless' completion style.
(use-package orderless
  :ensure t
  :custom
  ;; (orderless-style-dispatchers '(orderless-affix-dispatch))
  ;; (orderless-component-separator #'orderless-escapable-split-on-space)
  (completion-styles '(orderless basic))
  (completion-category-overrides '((file (styles partial-completion))))
  (completion-category-defaults nil) ;; Disable defaults, use our settings
  (completion-pcm-leading-wildcard t) ;; Emacs 31: partial-completion behaves like substring
)
#+END_SRC

*** Corfu
Documentation: https://github.com/minad/corfu

#+BEGIN_SRC elisp
(use-package corfu
  :ensure t
  :custom
  (corfu-cycle t)                ;; Enable cycling for `corfu-next/previous'
  (corfu-quit-at-boundary t)     ;; Always quit at completion boundary
  (corfu-quit-no-match t)        ;; Quit when there is no match
  (corfu-preview-current nil)    ;; Disable current candidate preview
  (corfu-preselect 'prompt)      ;; Preselect the prompt
  (corfu-on-exact-match 'insert) ;; Configure handling of exact matches

  ;; Enable Corfu only for certain modes. See also `global-corfu-modes'.
  ;; :hook ((prog-mode . corfu-mode)
  ;;        (shell-mode . corfu-mode)
  ;;        (eshell-mode . corfu-mode))

  :init
  (global-corfu-mode)
  
  :config
  (setq corfu-auto t
        corfu-auto-delay 0.1
        corfu-auto-trigger "." ;; Custom trigger characters
        corfu-quit-no-match 'separator) ;; or t
  ;; Enable optional extension modes:
  ;; (corfu-history-mode)
  ;; (corfu-popupinfo-mode)
  )

;; A few more useful configurations...
(use-package emacs
  :custom
  ;; TAB cycle if there are only few candidates
  (completion-cycle-threshold 3)

  ;; Enable indentation+completion using the TAB key.
  ;; `completion-at-point' is often bound to M-TAB.
  (tab-always-indent 'complete)

  ;; Emacs 30 and newer: Disable Ispell completion function.
  ;; Try `cape-dict' as an alternative.
  (text-mode-ispell-word-completion nil)

  ;; Hide commands in M-x which do not apply to the current mode.  Corfu
  ;; commands are hidden, since they are not used via M-x. This setting is
  ;; useful beyond Corfu.
  (read-extended-command-predicate #'command-completion-default-include-p))
#+END_SRC
*** Vertico
#+BEGIN_SRC elisp
;; Enable Vertico.
(use-package vertico
  :ensure t
  
  :custom
  ;; (vertico-scroll-margin 0) ;; Different scroll margin
  (vertico-count 20) ;; Show more candidates
  (vertico-resize nil) ;; Grow and shrink the Vertico minibuffer
  (vertico-cycle t) ;; Enable cycling for `vertico-next/previous'
  :init
  (vertico-mode))

;; Emacs minibuffer configurations.
(use-package emacs
  :custom
  ;; Enable context menu. `vertico-multiform-mode' adds a menu in the minibuffer
  ;; to switch display modes.
  (context-menu-mode t)
  ;; Support opening new minibuffers from inside existing minibuffers.
  (enable-recursive-minibuffers t)
  ;; Hide commands in M-x which do not work in the current mode.  Vertico
  ;; commands are hidden in normal buffers. This setting is useful beyond
  ;; Vertico.
  (read-extended-command-predicate #'command-completion-default-include-p)
  ;; Do not allow the cursor in the minibuffer prompt
  (minibuffer-prompt-properties
   '(read-only t cursor-intangible t face minibuffer-prompt)))
#+END_SRC
*** Cape
#+BEGIN_SRC elisp
;; Add extensions
(use-package cape
  :ensure t
  ;; Bind prefix keymap providing all Cape commands under a mnemonic key.
  ;; Press C-c p ? to for help.
  :bind ("C-c p" . cape-prefix-map) ;; Alternative key: M-<tab>, M-p, M-+
  ;; Alternatively bind Cape commands individually.
  ;; :bind (("C-c p d" . cape-dabbrev)
  ;;        ("C-c p h" . cape-history)
  ;;        ("C-c p f" . cape-file)
  ;;        ...)
  :init
  ;; Add to the global default value of `completion-at-point-functions' which is
  ;; used by `completion-at-point'.  The order of the functions matters, the
  ;; first function returning a result wins.  Note that the list of buffer-local
  ;; completion functions takes precedence over the global list.
  (add-hook 'completion-at-point-functions #'cape-dabbrev)
  (add-hook 'completion-at-point-functions #'cape-file)
  (add-hook 'completion-at-point-functions #'cape-elisp-block)
  (add-hook 'completion-at-point-functions #'cape-history)
  ;; ...
)
#+END_SRC
*** Marginalia
The purpose of this package is to provide additional information in the mini-buffer, for example the start of the documentation of a function, when said function is displayed in said minibuffer.

The following use-package macro is straight from the [[https://github.com/minad/marginalia][official documentation]] (I just added =:ensure t=). 
#+BEGIN_SRC elisp 
  ;; Enable rich annotations using the Marginalia package
  (use-package marginalia
    :ensure t
    ;; Bind `marginalia-cycle' locally in the minibuffer.  To make the binding
    ;; available in the *Completions* buffer, add it to the
    ;; `completion-list-mode-map'.
    :bind (:map minibuffer-local-map
           ("M-A" . marginalia-cycle))

    ;; The :init section is always executed.
    :init
    ;; Marginalia must be activated in the :init section of use-package such that
    ;; the mode gets enabled right away. Note that this forces loading the
    ;; package.
    (marginalia-mode))
#+END_SRC
*** Consult
Copy/pasted from [[https://github.com/minad/consult?tab=readme-ov-file#use-package-example][the officiel doc]].


#+BEGIN_SRC elisp
(global-unset-key (kbd "M-x"))

  (use-package consult
      :ensure t
      ;; Replace bindings. Lazily loaded by `use-package'.
      :bind (;; C-c bindings in `mode-specific-map'
             ("C-c M-x" . consult-mode-command)
             ([remap Info-search] . consult-info)
             ;; C-x bindings in `ctl-x-map'
             ("C-x M-:" . consult-complex-command)     ;; orig. repeat-complex-command
             ("C-x b" . consult-buffer)                ;; orig. switch-to-buffer
             ("C-x p b" . consult-project-buffer)      ;; orig. project-switch-to-buffer
             ;; Other custom bindings
             ("M-V" . consult-yank-pop)                ;; orig. yank-pop
             ;; M-g bindings in `goto-map'
             ("M-x g" . consult-goto-line)             ;; orig. goto-line
             ("M-x o" . consult-outline)               ;; Alternative: consult-org-heading
             ("M-x m" . consult-mark)
             ("M-x k" . consult-global-mark)
             ("M-x i" . consult-imenu)
             ("M-x I" . consult-imenu-multi)
             ;; M-s bindings in `search-map'
             ("M-x f" . consult-find)                  ;; Alternative: consult-fd
             ("M-x l" . consult-locate)
             ("M-x G" . consult-grep)
             ;("M-x G" . consult-git-grep)
             ("M-x r" . consult-ripgrep)
             ("M-x l" . consult-line)
             ("M-x L" . consult-line-multi)
             ;; ("M-s k" . consult-keep-lines)
             ;; ("M-s u" . consult-focus-lines)
             ;; Isearch integration
             ;("M-s e" . consult-isearch-history)
      ;;        :map isearch-mode-map
      ;;        ("M-e" . consult-isearch-history)         ;; orig. isearch-edit-string
      ;;        ("M-s e" . consult-isearch-history)       ;; orig. isearch-edit-string
      ;;        ("M-s l" . consult-line)                  ;; needed by consult-line to detect isearch
      ;;        ("M-s L" . consult-line-multi)            ;; needed by consult-line to detect isearch
      ;;        ;; Minibuffer history
      ;;        :map minibuffer-local-map
      ;;        ("M-s" . consult-history)                 ;; orig. next-matching-history-element
      ;;        ("M-r" . consult-history)                ;; orig. previous-matching-history-element
             )

      ;; ;; The :init configuration is always executed (Not lazy)
      :init

      ;; Tweak the register preview for `consult-register-load',
      ;; `consult-register-store' and the built-in commands.  This improves the
      ;; register formatting, adds thin separator lines, register sorting and hides
      ;; the window mode line.
      (advice-add #'register-preview :override #'consult-register-window)
      (setopt register-preview-delay 0.5)

      ;; Use Consult to select xref locations with preview
      (setopt xref-show-xrefs-function #'consult-xref
              xref-show-definitions-function #'consult-xref)

      ;; Configure other variables and modes in the :config section,
      ;; after lazily loading the package.
      :config

      ;; Optionally configure preview. The default value
      ;; is 'any, such that any key triggers the preview.
      ;; (setq consult-preview-key 'any)
      ;; (setq consult-preview-key "M-.")
      ;; (setq consult-preview-key '("S-<down>" "S-<up>"))
      ;; For some commands and buffer sources it is useful to configure the
      ;; :preview-key on a per-command basis using the `consult-customize' macro.
      (consult-customize
       consult-theme :preview-key '(:debounce 0.2 any)
       consult-ripgrep consult-git-grep consult-grep consult-man
       consult-bookmark consult-recent-file consult-xref
       consult-source-bookmark consult-source-file-register
       consult-source-recent-file consult-source-project-recent-file
       ;; :preview-key "M-."
       :preview-key '(:debounce 0.4 any))

      (setopt consult-narrow-key "<") ;; "C-+"

      ;; Optionally make narrowing help available in the minibuffer.
      ;; You may want to use `embark-prefix-help-command' or which-key instead.
      ;; (keymap-set consult-narrow-map (concat consult-narrow-key " ?") #'consult-narrow-help)
    )
#+END_SRC
** TODO Yasnippet
** Yasnippet

#+BEGIN_SRC emacs-lisp 
(use-package yasnippet
  :ensure t
  :hook
  (prg-mode . yas-minor-mode)
  )
#+END_SRC
** Hyperbole
#+BEGIN_SRC elisp
  (use-package hyperbole
    :ensure t
    )


#+END_SRC

** Custom moving/editing commands
First, a small helper functions: it unsets keyboard shortcut before assigning it to its new meaning.
   
#+BEGIN_SRC emacs-lisp
(defun pi2-6-global-set-key (keys func)
  (global-unset-key keys)
  (local-unset-key keys)
  (global-set-key keys func))
#+END_SRC

Now, the main function sets all the common keybindings that I use (many of which are based on an old ergoemacs version that I used a lot).

#+BEGIN_SRC emacs-lisp
  (defun pi2-6-reset-keys()
    "Sets all the keybindings at once."
    (interactive)

    (cua-mode)
    
    ;(global-unset-key "C-p")
    ;(local-unset-key  "C-p")
  					; -- main functions
    (pi2-6-global-set-key (kbd "M-SPC") 'set-mark-command)
    (pi2-6-global-set-key (kbd "M-a") 'execute-extended-command)
    (pi2-6-global-set-key (kbd "M-ù") 'execute-extended-command) ;; backup in case a mode redefines M-a

  					; -- movements within sentences
    (pi2-6-global-set-key (kbd "M-l") 'forward-char)
    (pi2-6-global-set-key (kbd "M-o") 'forward-word)
    (pi2-6-global-set-key (kbd "M-j") 'backward-char)
    (pi2-6-global-set-key (kbd "M-u") 'backward-word)
    (pi2-6-global-set-key (kbd "M-h") 'move-beginning-of-line)
    (pi2-6-global-set-key (kbd "M-m") 'move-end-of-line)
    (pi2-6-global-set-key (kbd "M-i") 'previous-line)
    (pi2-6-global-set-key (kbd "M-k") 'next-line)

  					; -- bigger movements
    (pi2-6-global-set-key (kbd "M-p") 'recenter-top-bottom)
    (pi2-6-global-set-key (kbd "C-f") 'pi2-6-occur-in-project-or-folder)
    (pi2-6-global-set-key (kbd "M-;") 'isearch-forward)
    (pi2-6-global-set-key (kbd "M-:") 'isearch-backward)
    (pi2-6-global-set-key (kbd "M-\" g") 'goto-line)
    (pi2-6-global-set-key (kbd "M-\" s") 'pi2-6-save-anchor)
    (pi2-6-global-set-key (kbd "M-\" b") 'pi2-6-back-to-anchor)

                                          ; -- outline
    (pi2-6-global-set-key (kbd "M-é") 'outline-forward-same-level)
    (pi2-6-global-set-key (kbd "M-&") 'outline-backward-same-level)
    (pi2-6-global-set-key (kbd "C-<tab>") 'outline-cycle)
    (pi2-6-global-set-key (kbd "C-M-<tab>") 'outline-cycle-buffer)
    

  					; -- advanced interaction with region
  					;(pi2-6-global-set-key (kbd "M-\" m") 'pi2-6-improved-selector)

  					; -- deleting
    (pi2-6-global-set-key (kbd "M-f") 'delete-char)
    (pi2-6-global-set-key (kbd "M-r") 'kill-word)
    (pi2-6-global-set-key (kbd "M-d") 'delete-backward-char)
    (pi2-6-global-set-key (kbd "M-e") 'backward-kill-word)
    (pi2-6-global-set-key (kbd "M-g") 'kill-line)

  					; -- undo/redo
    (pi2-6-global-set-key (kbd "M-z") 'undo)
    (pi2-6-global-set-key (kbd "M-y") 'undo-redo)
    (pi2-6-global-set-key (kbd "M--") 'repeat)

  					; -- kill ring
    ;; (pi2-6-global-set-key (kbd "M-c") 'kill-ring-save)
    ;; (pi2-6-global-set-key (kbd "M-v") 'yank)
    
  					; -- more sophisticated text interaction
    (pi2-6-global-set-key (kbd "M-q") 'fill-paragraph)
    (pi2-6-global-set-key (kbd "C-_") 'yas-expand)
    (pi2-6-global-set-key (kbd "M-'") 'comment-dwim)

  					; -- insertions
    (pi2-6-global-set-key (kbd "M-\" i") 'pi2-6-insert-time-stamp)
    (pi2-6-global-set-key (kbd "M-\" t") 'pi2-6-insert-current-time)

  					; -- rectangle manipulations
    (pi2-6-global-set-key (kbd "C-x r x") 'kill-rectangle)
    (pi2-6-global-set-key (kbd "C-x r c") 'copy-rectangle-as-kill)
    (pi2-6-global-set-key (kbd "C-x r v") 'yank-rectangle)
    (pi2-6-global-set-key (kbd "C-x r n") 'rectangle-number-lines)
    (pi2-6-global-set-key (kbd "C-x r i") 'string-rectangle)

  					; -- ispell/flyspell
    (pi2-6-global-set-key (kbd "M-\" l") 'pi2-6-flyspell-mode)


  					; -- interacting with buffers
    (pi2-6-global-set-key (kbd "C-<prior>") 'previous-buffer)
    (pi2-6-global-set-key (kbd "C-<next>")  'next-buffer)
    (pi2-6-global-set-key (kbd "C-r")       'revert-buffer)
    (pi2-6-global-set-key (kbd "C-S-b")     'ibuffer)
    (pi2-6-global-set-key (kbd "C-b")       'consult-buffer)


  					; -- interacting with files
    (pi2-6-global-set-key (kbd "C-o") 'pi2-6-find-file-in-project-or-not)
    (pi2-6-global-set-key (kbd "C-S-o") 'find-file)
    (pi2-6-global-set-key (kbd "C-c C-o") 'pi2-6/open-at-point)
    (pi2-6-global-set-key (kbd "M-\" c") 'pi2-6-copy-link-to-current-file)
    (pi2-6-global-set-key (kbd "M-\" o") 'pi2-6-open-terminal-in-directory)
    (pi2-6-global-set-key (kbd "M-\" f") 'pi2-6-open-file-browser-in-directory)
    (pi2-6-global-set-key (kbd "M-à") 'pi2-6-open-dired)

  					; -- interacting with windows
    (pi2-6-global-set-key (kbd "M-Q") 'delete-window)
    (pi2-6-global-set-key (kbd "M-s") 'other-window)
    (pi2-6-global-set-key (kbd "M-S") 'delete-other-windows)
    (pi2-6-global-set-key (kbd "C-b") 'consult-buffer)


  					; -- interacting with frames
    (pi2-6-global-set-key (kbd "C-S-n") 'make-frame-command)
    (pi2-6-global-set-key (kbd "C-w")   'kill-buffer)
    (pi2-6-global-set-key (kbd "C-s")   'save-buffer)

  					; -- meuporg
    (pi2-6-global-set-key (kbd "C-! d") 'xref-find-definitions-other-window)
    (pi2-6-global-set-key (kbd "C-! h") 'lsp-describe-thing-at-point)
    (pi2-6-global-set-key (kbd "C-! b") 'xref-go-back)
    (pi2-6-global-set-key (kbd "C-! j") 'consult-outline)
    (pi2-6-global-set-key (kbd "C-! o") 'pi2-6/open-at-point)
    (pi2-6-global-set-key (kbd "C-! c") 'pi2-6/vulpea-action)
    (pi2-6-global-set-key (kbd "C-! f") 'vulpea-find)
    (pi2-6-global-set-key (kbd "C-! n") 'org-roam-node-insert)
    (pi2-6-global-set-key (kbd "C-! a") 'org-agenda)
    (pi2-6-global-set-key (kbd "C-! !") 'pi2-6/dashboard)
    )



  (add-hook 'after-init-hook 'pi2-6-reset-keys)
  (add-hook 'org-mode-hook 'pi2-6-reset-keys)
  (add-hook 'c-mode-common-hook 'pi2-6-reset-keys)
#+END_SRC

* Programming
** Appearance
*** C-like languages
Using "bsd", a proper style of indentation for C(-like) languages,
much better than the GNU style in my opinion.

We then set the offset to 4 characters, and remove all tabs.

#+BEGIN_SRC elisp
(setopt c-default-style "bsd")
(setopt c-basic-offset 4)
(setopt indent-tabs-mode nil)
#+END_SRC
*** Python
For python, we only need to set the value of the default indent.
#+BEGIN_SRC elisp
(setopt python-indent-offset 4)
#+END_SRC
** TODO LSP

#+BEGIN_SRC elisp
  (use-package lsp-mode
    :ensure t
    ;:config
    ;(define-key lsp-mode-map [remap xref-find-apropos] #'helm-lsp-workspace-symbol)

    :hook
    (python-mode . lsp)
    (c++-mode . lsp)
    (c-mode . lsp)
    )


  (use-package lsp-ui
    :ensure t
    :config
    (setq
     lsp-ui-peek-enable t
     )

    :hook
    (lsp-mode . lsp-ui-mode)
    )
#+END_SRC


None of the python language servers I tried handle =cython=. Neither microsoft's =pyright= (which comes with as an entire nodeJS framework oO), nor the default =pylsp=, nor =jedi=. I haven't tried Palantir's because I have a soul.

#+BEGIN_SRC elisp
;; (use-package lsp-jedi
;;   :ensure t)

;; (use-package lsp-pyright
;;   :ensure t
;;   :custom (lsp-pyright-langserver-command "pyright") ;; or basedpyright
;;   :hook (python-mode . (lambda ()
;;                          (require 'lsp-pyright)
;;                          (lsp))))  ; or lsp-deferred

;; (add-to-list 'lsp-disabled-clients 'pylsp)
;; (add-to-list 'lsp-disabled-clients 'pyright)


#+END_SRC
** Specific tools
*** Cmake
#+BEGIN_SRC elisp
  (use-package cmake-mode
    :ensure t
    )
#+END_SRC
*** LaTeX
Auctex really simplifies handling LaTeX projects. I take this opportunity to activate two more modes when a LaTeX file is opened:
- TeX-source-correlate-mode :: allows backward searches whereby clicking on a spot on a pdf file opens a buffer containing the corresponding LaTeX code, and
- reftex-mode :: a sophisticated minor mode which handles references, both in-file ones (\ref) and external citations (\cite). Also provides the command =reftex-toc= (bound to =C-c == by default) which enables a quick navigation within a document structure independently from the way it is split into distinct LaTeX files.

#+BEGIN_SRC elisp
  (use-package tex
    :ensure auctex
    
    :hook
    ((LaTeX-mode . TeX-source-correlate-mode)
     (LaTeX-mode . reftex-mode)))
#+END_SRC
* Dashboard

#+BEGIN_SRC elisp
  (require 'widget)
  (require 'org)
#+END_SRC

** General Helper Functions
#+BEGIN_SRC elisp
  (defun pi2-6/pretty-tags(tags)
    (let ((double-dots (propertize ":" 'face 'org-tag)))
      (s-concat
       (mapconcat
        (lambda(tag)
          (format "%s%s" double-dots (propertize tag 'face (list (org-get-tag-face tag) 'org-tag))))
        tags)
       (if tags double-dots ""))))

#+END_SRC

#+BEGIN_SRC elisp
  (defun pi2-6/create-file-link(title path tags)
    "Create a widget link to a given file with pretty tags."
    (insert "  ")
    (widget-create 'link
                   :tag (s-concat (propertize "[→]" 'face 'org-link) " " title)
                   :button-prefix ""
                   :button-suffix ""
                   :button-face '(:weight 'normal)
                   :action `(lambda (widget &optional event)
                              (find-file ,path)))
    (insert "  " (pi2-6/pretty-tags tags) "\n"))


  (defun pi2-6/dashboard-header (title depth)
    "Insert a fontified header."
    (pcase depth
      (1 (insert "\n\n" (propertize (format "* %s" title ) 'face 'org-level-1) "\n\n"))
      (2 (insert (propertize (format "* %s" title ) 'face 'org-level-2) "\n"))
      (_ (insert title))))

#+END_SRC

** Generating Specific Content
*** Ongoing projects
#+BEGIN_SRC elisp
  (defun pi2-6/create-project-link-widget(proj)
    (let ((proj-tags (remove "ongoingWork" (vulpea-note-tags proj)))
          (proj-title (vulpea-note-title proj))
          (proj-path (vulpea-note-path proj)))
      (pi2-6/create-file-link proj-title proj-path proj-tags)))      


  (defun pi2-6/dashboard-ongoing ()
    "Creates a list of widget links by pulling all the notes tagged
     ongoingWork."
    (pi2-6/dashboard-header "Ongoing Work" 1)
    (mapcar 'pi2-6/create-project-link-widget
            (vulpea-db-query-by-tags-every '("ongoingWork"))))

#+END_SRC

*** Dotfiles
#+BEGIN_SRC elisp
  (defun pi2-6/dashboard-dotfiles()
    "Inserts a section linking to the dotfiles."
    (pi2-6/dashboard-header "Maintenance" 1)
    (pi2-6/dashboard-header ".files" 2)
    (pi2-6/create-file-link "emacs config" "~/dotfiles/emacs/config.org" nil)
    (pi2-6/create-file-link "SWAY config" "~/dotfiles/sway.org" nil)
    (pi2-6/create-file-link "Scripts" "~/dotfiles/scripts.org" nil)
    (pi2-6/dashboard-header "Workshop" 2)
    (pi2-6/create-file-link "Color theme (cyanide-theme)" "~/workshop/cyanide-theme/readme.org" nil)
    (pi2-6/create-file-link "Meuporg" "~/workshop/meuporg/readme.org" nil))
#+END_SRC

*** Reviews
#+BEGIN_SRC elisp
  (defun pi2-6/dashboard-reviews ()
    "Inserts widgets to access reviews."
    (pi2-6/dashboard-header "Reviews" 1)
    
    )
#+END_SRC

*** Widgets
#+BEGIN_SRC elisp
    (defun pi2-6/dashboard-papers-by-tags ()
      "Creates a list of widget links by pullin all the notes tagged"
      (widget-create 'editable-field
                     :size 30
                     :format "Find papers with tags: %v "
                     :value ""
                     :notify (lambda (widget &rest ignore)
                               (setq pi2-6/dashboard-paper-query-tag (widget-value widget))))
      (widget-create 'push-button 
                     :notify (lambda (&rest ignore)
                               (vulpea-visit
                                (vulpea-select-from
                                 (format "Papers with tag %s" pi2-6/dashboard-paper-query-tag)
                                 (vulpea-db-query-by-tags-every
                                  (cons "paper"
                                          (split-string pi2-6/dashboard-paper-query-tag ":"))))))
                     "find")
      (insert "\n"))

#+END_SRC

** Main Function
#+BEGIN_SRC elisp
  (defun pi2-6/dashboard ()
    "Create a landing page dashboard."
    (interactive)
    (let ((buf (get-buffer-create "*Dashboard*")))
      (with-current-buffer buf
        (let ((inhibit-read-only t))
          (erase-buffer)
          (insert (propertize "-*-  Dashboard  -*-" 'face 'org-document-title))
          (insert "\n")

          (pi2-6/dashboard-ongoing)
          
          (pi2-6/dashboard-reviews)

          (pi2-6/dashboard-dotfiles)

          (pi2-6/dashboard-header "Vulpea/Roam" 1)
          
          (pi2-6/dashboard-papers-by-tags)
          
          (insert "\n\n")
          

          (use-local-map widget-keymap)
          (widget-setup)
          (switch-to-buffer buf)
          (goto-char (point-min))
          (forward-line 3)))))
#+END_SRC
